# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEqSxC7xkTwj2L0OhYsDMHo4JD934QP-
"""

# Install scapy inside Colab (temporary, automatic)
!pip -q install scapy

from scapy.all import IP, TCP, UDP, ICMP, ARP, Ether, Raw
from datetime import datetime

# Function to analyze packets
def analyze_packet(packet):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print("\n" + "=" * 60)
    print(f"[*] Packet Generated at {timestamp}")
    print("=" * 60)

    if packet.haslayer(Ether):
        eth = packet[Ether]
        print(f"[ETH] Src MAC : {eth.src}")
        print(f"[ETH] Dst MAC : {eth.dst}")

    if packet.haslayer(ARP):
        arp = packet[ARP]
        op = "Request" if arp.op == 1 else "Reply"
        print(f"[ARP] Operation : {op}")
        print(f"[ARP] Sender IP : {arp.psrc}")
        print(f"[ARP] Target IP : {arp.pdst}")
        return

    if packet.haslayer(IP):
        ip = packet[IP]
        print(f"[IP] Source      : {ip.src}")
        print(f"[IP] Destination : {ip.dst}")
        print(f"[IP] TTL         : {ip.ttl}")

        if packet.haslayer(TCP):
            tcp = packet[TCP]
            print(f"[TCP] Src Port : {tcp.sport}")
            print(f"[TCP] Dst Port : {tcp.dport}")

        elif packet.haslayer(UDP):
            udp = packet[UDP]
            print(f"[UDP] Src Port : {udp.sport}")
            print(f"[UDP] Dst Port : {udp.dport}")

        elif packet.haslayer(ICMP):
            icmp = packet[ICMP]
            print(f"[ICMP] Type    : {icmp.type}")
            print(f"[ICMP] Code    : {icmp.code}")

        if packet.haslayer(Raw):
            data = packet[Raw].load
            print(f"[DATA] Payload : {data[:50]}")

# Create sample packets (simulation)
packets = []

# TCP Packet
packets.append(Ether()/IP(src="192.168.1.1", dst="8.8.8.8")/TCP(sport=1234, dport=80)/Raw(load="GET / HTTP/1.1"))

# UDP Packet
packets.append(Ether()/IP(src="10.0.0.1", dst="8.8.4.4")/UDP(sport=5000, dport=53)/Raw(load="DNS Query"))

# ICMP Packet
packets.append(Ether()/IP(src="192.168.0.5", dst="1.1.1.1")/ICMP())

# ARP Packet
packets.append(Ether()/ARP(psrc="192.168.1.10", pdst="192.168.1.1"))

# Analyze all packets
for pkt in packets:
    analyze_packet(pkt)

print("\n" + "=" * 60)
print("✔ Simulation Complete (Colab Compatible)")
print("=" * 60)