# -*- coding: utf-8 -*-
"""Task 3 CodeAlpha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_WAOUr_mUKe4KGp6PEArgLakKhVP4EFJ
"""

# 🔐 Secure Coding Review - CodeAlpha Task 3

from IPython.display import display, Markdown
import hashlib

# ---------------- TITLE ----------------
display(Markdown("# 🔐 Secure Coding Review"))
display(Markdown("### CodeAlpha Internship - Task 3\n---"))

# ---------------- INTRO ----------------
display(Markdown("## 📌 Application Selected"))
display(Markdown("Python-based Login System\n"))

# ---------------- VULNERABLE CODE ----------------
display(Markdown("## ⚠️ Vulnerable Code Example"))
vulnerable_code = """
username = input("Enter username: ")
password = input("Enter password: ")

if username == "admin" and password == "1234":
    print("Login Successful")
else:
    print("Login Failed")
"""
print(vulnerable_code)

# ---------------- ANALYSIS ----------------
display(Markdown("## 🔍 Identified Security Issues"))

issues = [
    "Hardcoded credentials (admin / 1234)",
    "Password stored in plain text",
    "No input validation",
    "No rate limiting (unlimited attempts)",
    "No logging or monitoring"
]

for i, issue in enumerate(issues, 1):
    print(f"{i}. {issue}")

# ---------------- IMPACT ----------------
display(Markdown("## 🚨 Impact of Vulnerabilities"))

impacts = [
    "Easy for attackers to guess credentials",
    "Sensitive data exposure risk",
    "System vulnerable to brute force attacks",
    "No tracking of malicious activity"
]

for i, impact in enumerate(impacts, 1):
    print(f"{i}. {impact}")

# ---------------- SECURE CODE ----------------
display(Markdown("## ✅ Secure Code Implementation"))

secure_code = """
import hashlib

stored_username = "admin"
stored_password = hashlib.sha256("1234".encode()).hexdigest()

username = input("Enter username: ")
password = input("Enter password: ")

hashed_input = hashlib.sha256(password.encode()).hexdigest()

if username == stored_username and hashed_input == stored_password:
    print("Login Successful")
else:
    print("Login Failed")
"""
print(secure_code)

# ---------------- DEMO RUN ----------------
display(Markdown("## 🧪 Test the Secure Login System"))

stored_username = "admin"
stored_password = hashlib.sha256("1234".encode()).hexdigest()

username = input("Enter username: ")
password = input("Enter password: ")

hashed_input = hashlib.sha256(password.encode()).hexdigest()

if username == stored_username and hashed_input == stored_password:
    print("✅ Login Successful")
else:
    print("❌ Login Failed")

# ---------------- BEST PRACTICES ----------------
display(Markdown("## 🛡️ Best Practices for Secure Coding"))

best_practices = [
    "Use password hashing (bcrypt, SHA-256)",
    "Avoid hardcoding credentials",
    "Validate user inputs",
    "Limit login attempts (rate limiting)",
    "Enable logging and monitoring",
    "Use Multi-Factor Authentication (MFA)"
]

for i, practice in enumerate(best_practices, 1):
    print(f"{i}. {practice}")

# ---------------- TOOLS ----------------
display(Markdown("## 🧰 Tools for Security Analysis"))
print("• Bandit (Python security analyzer)")
print("• Static code analyzers")
print("• Manual code review techniques")

# ---------------- CONCLUSION ----------------
display(Markdown("## 📊 Conclusion"))
display(Markdown("""
This secure coding review identified critical vulnerabilities in a simple login system.
By applying hashing and security best practices, the system becomes safer and more reliable.
"""))