# -*- coding: utf-8 -*-
"""Task 2 CodeAlpha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rc0ltngDNrNmA0C-Z3NAOyMMdz6RnxqT
"""

# Phishing Awareness Training - CodeAlpha Task 2

from IPython.display import display, Markdown, Image

# Title
display(Markdown("# 🛡️ Phishing Awareness Training"))
display(Markdown("### Learn how to stay safe from cyber attacks\n---"))

# Section 1: Introduction
display(Markdown("## 📌 What is Phishing?"))
display(Markdown("Phishing is a cyber attack where attackers trick users into revealing sensitive information like passwords, OTPs, or bank details.\n"))

# Section 2: Types
display(Markdown("## 🎯 Types of Phishing"))
display(Markdown("""
- Email Phishing
- Spear Phishing
- Smishing (SMS)
- Vishing (Calls)
"""))

# Section 3: Recognizing Emails
display(Markdown("## 📧 How to Recognize Phishing Emails"))
display(Markdown("""
- Unknown sender email
- Urgent or threatening language
- Suspicious links
- Spelling mistakes
"""))

# Section 4: Fake Websites
display(Markdown("## 🌐 How to Identify Fake Websites"))
display(Markdown("""
- Check HTTPS (🔒)
- Look for wrong domain spelling
- Avoid clicking unknown links
"""))

# Section 5: Social Engineering
display(Markdown("## 🧠 Social Engineering Tactics"))
display(Markdown("""
- Impersonation (bank/company)
- Urgency ("Act now!")
- Fear ("Account blocked!")
- Free offers
"""))

# Section 6: Safety Tips
display(Markdown("## ✅ Best Practices"))
display(Markdown("""
- Never share OTP/password
- Verify links before clicking
- Use strong passwords
- Enable 2FA
"""))

# Section 7: Example Image
display(Markdown("## 🖼️ Example of Phishing Email"))
display(Image(url="https://upload.wikimedia.org/wikipedia/commons/5/5c/PhishingEmailExample.png"))

# Quiz Section
display(Markdown("## 📝 Quick Quiz"))

score = 0

# Question 1
ans1 = input("Q1: Email asks for your password urgently. Is it phishing? (yes/no): ")
if ans1.lower() == "yes":
    print("✅ Correct!")
    score += 1
else:
    print("❌ Wrong!")

# Question 2
ans2 = input("Q2: Website URL is 'amaz0n-login.com'. Safe? (yes/no): ")
if ans2.lower() == "no":
    print("✅ Correct!")
    score += 1
else:
    print("❌ Wrong!")

# Question 3
ans3 = input("Q3: You get a free lottery message from unknown sender. Trust it? (yes/no): ")
if ans3.lower() == "no":
    print("✅ Correct!")
    score += 1
else:
    print("❌ Wrong!")

# Final Score
print("\n🎯 Your Score:", score, "/ 3")

if score == 3:
    print("🏆 Excellent! You are phishing aware.")
elif score == 2:
    print("👍 Good! Stay alert.")
else:
    print("⚠️ Be careful! Learn more about phishing.")

